name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: Mateo00DelLungo/Practico_01@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE : "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_SHORT_INFO: "False"
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: Mateo00DelLungo/Practicos # optional
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: -> # optional
          CODE_LANG: python # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 5 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML JSON TOML # optional
          ### commit
          
          
          AUTHOR_NAME: Mateo # optional
         # you can populate email-id with secrets instead
